/**
 * Chain information map
 * Contains all static metadata for each supported blockchain network
 */

import { Chain, ChainType } from '@sudobility/types';
import type { ChainInfo } from './rpc-helpers';

/**
 * Consolidated chain information map
 * Contains all static metadata for each supported blockchain network
 */
export const CHAIN_INFO_MAP: Record<Chain, ChainInfo> = {
  // Ethereum
  [Chain.ETH_MAINNET]: {
    chainType: ChainType.EVM,
    chainId: 1,
    name: 'Ethereum',
    alchemyNetwork: 'eth-mainnet',
    ankrNetwork: 'eth',
    metamaskNetwork: 'mainnet',
    explorerDomain: 'api.etherscan.io',
    explorerBrowserDomain: 'etherscan.io',
    usdcAddress: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48',
    isDev: false,
  },
  [Chain.ETH_SEPOLIA]: {
    chainType: ChainType.EVM,
    chainId: 11155111,
    name: 'Ethereum Sepolia',
    alchemyNetwork: 'eth-sepolia',
    ankrNetwork: 'eth_sepolia',
    metamaskNetwork: 'sepolia',
    explorerDomain: 'api-sepolia.etherscan.io',
    explorerBrowserDomain: 'sepolia.etherscan.io',
    usdcAddress: '0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238',
    isDev: true,
    mailerAddress: '0x8de9c081a31cbb14a5974b6b4a04aa8502a796f7',
    startingBlock: 9531686,
  },
  [Chain.ETH_GOERLI]: {
    chainType: ChainType.EVM,
    chainId: 5,
    name: 'Ethereum Goerli',
    alchemyNetwork: 'eth-goerli',
    ankrNetwork: 'eth_goerli',
    metamaskNetwork: 'goerli',
    explorerDomain: 'api-goerli.etherscan.io',
    explorerBrowserDomain: 'goerli.etherscan.io',
    usdcAddress: '0x07865c6E87B9F70255377e024ace6630C1Eaa37F',
    isDev: true,
  },

  // Polygon
  [Chain.POLYGON_MAINNET]: {
    chainType: ChainType.EVM,
    chainId: 137,
    name: 'Polygon',
    alchemyNetwork: 'polygon-mainnet',
    ankrNetwork: 'polygon',
    metamaskNetwork: 'polygon-mainnet',
    explorerDomain: 'api.polygonscan.com',
    explorerBrowserDomain: 'polygonscan.com',
    usdcAddress: '0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359',
    isDev: false,
  },
  [Chain.POLYGON_MUMBAI]: {
    chainType: ChainType.EVM,
    chainId: 80001,
    name: 'Polygon Mumbai',
    alchemyNetwork: 'polygon-mumbai',
    ankrNetwork: 'polygon_mumbai',
    metamaskNetwork: undefined,
    explorerDomain: 'api-testnet.polygonscan.com',
    explorerBrowserDomain: 'mumbai.polygonscan.com',
    usdcAddress: '0x9999f7Fea5938fD3b1E26A12c3f2fb024e194f97',
    isDev: true,
  },
  [Chain.POLYGON_AMOY]: {
    chainType: ChainType.EVM,
    chainId: 80002,
    name: 'Polygon Amoy',
    alchemyNetwork: 'polygon-amoy',
    ankrNetwork: 'polygon_amoy',
    metamaskNetwork: 'polygon-amoy',
    explorerDomain: 'api-amoy.polygonscan.com',
    explorerBrowserDomain: 'amoy.polygonscan.com',
    usdcAddress: '0x41E94Eb019C0762f9Bfcf9Fb1E58725BfB0e7582',
    isDev: true,
  },

  // Optimism
  [Chain.OPTIMISM_MAINNET]: {
    chainType: ChainType.EVM,
    chainId: 10,
    name: 'Optimism',
    alchemyNetwork: 'opt-mainnet',
    ankrNetwork: 'optimism',
    metamaskNetwork: 'optimism-mainnet',
    explorerDomain: 'api-optimistic.etherscan.io',
    explorerBrowserDomain: 'optimistic.etherscan.io',
    usdcAddress: '0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85',
    isDev: false,
  },
  [Chain.OPTIMISM_SEPOLIA]: {
    chainType: ChainType.EVM,
    chainId: 11155420,
    name: 'Optimism Sepolia',
    alchemyNetwork: 'opt-sepolia',
    ankrNetwork: 'optimism_sepolia',
    metamaskNetwork: 'optimism-sepolia',
    explorerDomain: 'api-sepolia-optimistic.etherscan.io',
    explorerBrowserDomain: 'sepolia-optimistic.etherscan.io',
    usdcAddress: '0x5fd84259d66Cd46123540766Be93DFE6D43130D7',
    isDev: true,
  },
  [Chain.OPTIMISM_GOERLI]: {
    chainType: ChainType.EVM,
    chainId: 420,
    name: 'Optimism Goerli',
    alchemyNetwork: 'opt-goerli',
    ankrNetwork: 'optimism_goerli',
    metamaskNetwork: undefined,
    explorerDomain: 'api-goerli-optimistic.etherscan.io',
    explorerBrowserDomain: 'goerli-optimistic.etherscan.io',
    usdcAddress: '0xe05606174bac4A6364B31bd0eCA4bf4dD368f8C6',
    isDev: true,
  },

  // Arbitrum
  [Chain.ARBITRUM_MAINNET]: {
    chainType: ChainType.EVM,
    chainId: 42161,
    name: 'Arbitrum',
    alchemyNetwork: 'arb-mainnet',
    ankrNetwork: 'arbitrum',
    metamaskNetwork: 'arbitrum-mainnet',
    explorerDomain: 'api.arbiscan.io',
    explorerBrowserDomain: 'arbiscan.io',
    usdcAddress: '0xaf88d065e77c8cC2239327C5EDb3A432268e5831',
    isDev: false,
  },
  [Chain.ARBITRUM_SEPOLIA]: {
    chainType: ChainType.EVM,
    chainId: 421614,
    name: 'Arbitrum Sepolia',
    alchemyNetwork: 'arb-sepolia',
    ankrNetwork: 'arbitrum_sepolia',
    metamaskNetwork: 'arbitrum-sepolia',
    explorerDomain: 'api-sepolia.arbiscan.io',
    explorerBrowserDomain: 'sepolia.arbiscan.io',
    usdcAddress: '0x75faf114eafb1BDbe2F0316DF893fd58CE46AA4d',
    isDev: true,
  },
  [Chain.ARBITRUM_GOERLI]: {
    chainType: ChainType.EVM,
    chainId: 421613,
    name: 'Arbitrum Goerli',
    alchemyNetwork: 'arb-goerli',
    ankrNetwork: 'arbitrum_goerli',
    metamaskNetwork: undefined,
    explorerDomain: 'api-goerli.arbiscan.io',
    explorerBrowserDomain: 'goerli.arbiscan.io',
    usdcAddress: '0xfd064A18f3BF249cf1f87FC203E90D8f650f2d63',
    isDev: true,
  },

  // Base
  [Chain.BASE_MAINNET]: {
    chainType: ChainType.EVM,
    chainId: 8453,
    name: 'Base',
    alchemyNetwork: 'base-mainnet',
    ankrNetwork: 'base',
    metamaskNetwork: undefined,
    explorerDomain: 'api.basescan.org',
    explorerBrowserDomain: 'basescan.org',
    usdcAddress: '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913',
    isDev: false,
  },
  [Chain.BASE_SEPOLIA]: {
    chainType: ChainType.EVM,
    chainId: 84532,
    name: 'Base Sepolia',
    alchemyNetwork: 'base-sepolia',
    ankrNetwork: 'base_sepolia',
    metamaskNetwork: undefined,
    explorerDomain: 'api-sepolia.basescan.org',
    explorerBrowserDomain: 'sepolia.basescan.org',
    usdcAddress: '0x036CbD53842c5426634e7929541eC2318f3dCF7e',
    isDev: true,
  },
  [Chain.BASE_GOERLI]: {
    chainType: ChainType.EVM,
    chainId: 84531,
    name: 'Base Goerli',
    alchemyNetwork: 'base-goerli',
    ankrNetwork: 'base_goerli',
    metamaskNetwork: undefined,
    explorerDomain: 'api-goerli.basescan.org',
    explorerBrowserDomain: 'goerli.basescan.org',
    usdcAddress: '0xF175520C52418dfE19C8098071a252da48Cd1C19',
    isDev: true,
  },

  // Avalanche
  [Chain.AVALANCHE_MAINNET]: {
    chainType: ChainType.EVM,
    chainId: 43114,
    name: 'Avalanche',
    alchemyNetwork: 'avax-mainnet',
    ankrNetwork: 'avalanche',
    metamaskNetwork: 'avalanche-mainnet',
    explorerDomain: 'api.snowtrace.io',
    explorerBrowserDomain: 'snowtrace.io',
    usdcAddress: '0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E',
    isDev: false,
  },
  [Chain.AVALANCHE_FUJI]: {
    chainType: ChainType.EVM,
    chainId: 43113,
    name: 'Avalanche Fuji',
    alchemyNetwork: 'avax-fuji',
    ankrNetwork: 'avalanche_fuji',
    metamaskNetwork: 'avalanche-fuji',
    explorerDomain: 'api-testnet.snowtrace.io',
    explorerBrowserDomain: 'testnet.snowtrace.io',
    usdcAddress: '0x5425890298aed601595a70AB815c96711a31Bc65',
    isDev: true,
  },

  // BNB Chain
  [Chain.BNB_MAINNET]: {
    chainType: ChainType.EVM,
    chainId: 56,
    name: 'BNB Chain',
    alchemyNetwork: 'bnb-mainnet',
    ankrNetwork: 'bsc',
    metamaskNetwork: undefined,
    explorerDomain: 'api.bscscan.com',
    explorerBrowserDomain: 'bscscan.com',
    usdcAddress: '0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d',
    isDev: false,
  },
  [Chain.BNB_TESTNET]: {
    chainType: ChainType.EVM,
    chainId: 97,
    name: 'BNB Chain Testnet',
    alchemyNetwork: 'bnb-testnet',
    ankrNetwork: 'bsc_testnet_chapel',
    metamaskNetwork: undefined,
    explorerDomain: 'api-testnet.bscscan.com',
    explorerBrowserDomain: 'testnet.bscscan.com',
    usdcAddress: '0x64544969ed7EBf5f083679233325356EbE738930',
    isDev: true,
  },

  // Gnosis Chain
  [Chain.GNOSIS_MAINNET]: {
    chainType: ChainType.EVM,
    chainId: 100,
    name: 'Gnosis',
    alchemyNetwork: 'gnosis-mainnet',
    ankrNetwork: 'gnosis',
    metamaskNetwork: undefined,
    explorerDomain: 'api.gnosisscan.io',
    explorerBrowserDomain: 'gnosisscan.io',
    usdcAddress: '0xDDAfbb505ad214D7b80b1f830fcCc89B60fb7A83',
    isDev: false,
  },
  [Chain.GNOSIS_CHIADO]: {
    chainType: ChainType.EVM,
    chainId: 10200,
    name: 'Gnosis Chiado',
    alchemyNetwork: 'gnosis-chiado',
    ankrNetwork: 'gnosis_chiado',
    metamaskNetwork: undefined,
    explorerDomain: 'api-chiado.gnosisscan.io',
    explorerBrowserDomain: 'gnosis-chiado.blockscout.com',
    usdcAddress: undefined,
    isDev: true,
  },

  // Celo
  [Chain.CELO_MAINNET]: {
    chainType: ChainType.EVM,
    chainId: 42220,
    name: 'Celo',
    alchemyNetwork: 'celo-mainnet',
    ankrNetwork: 'celo',
    metamaskNetwork: undefined,
    explorerDomain: 'api.celoscan.io',
    explorerBrowserDomain: 'celoscan.io',
    usdcAddress: '0xcebA9300f2b948710d2653dD7B07f33A8B32118C',
    isDev: false,
  },
  [Chain.CELO_ALFAJORES]: {
    chainType: ChainType.EVM,
    chainId: 44787,
    name: 'Celo Alfajores',
    alchemyNetwork: 'celo-alfajores',
    ankrNetwork: 'celo_alfajores',
    metamaskNetwork: undefined,
    explorerDomain: 'api-alfajores.celoscan.io',
    explorerBrowserDomain: 'alfajores.celoscan.io',
    usdcAddress: '0x2F25deB3848C207fc8E0c34035B3Ba7fC157602B',
    isDev: true,
  },

  // zkSync
  [Chain.ZKSYNC_MAINNET]: {
    chainType: ChainType.EVM,
    chainId: 324,
    name: 'zkSync',
    alchemyNetwork: 'zksync-mainnet',
    ankrNetwork: 'zksync_era',
    metamaskNetwork: undefined,
    explorerDomain: 'api-era.zksync.network',
    explorerBrowserDomain: 'explorer.zksync.io',
    usdcAddress: '0x1d17CBcF0D6D143135aE902365D2E5e2A16538D4',
    isDev: false,
  },
  [Chain.ZKSYNC_SEPOLIA]: {
    chainType: ChainType.EVM,
    chainId: 300,
    name: 'zkSync Sepolia',
    alchemyNetwork: 'zksync-sepolia',
    ankrNetwork: 'zksync_era_sepolia',
    metamaskNetwork: undefined,
    explorerDomain: 'api-sepolia-era.zksync.network',
    explorerBrowserDomain: 'sepolia.explorer.zksync.io',
    usdcAddress: undefined,
    isDev: true,
  },

  // Linea
  [Chain.LINEA_MAINNET]: {
    chainType: ChainType.EVM,
    chainId: 59144,
    name: 'Linea',
    alchemyNetwork: 'linea-mainnet',
    ankrNetwork: 'linea',
    metamaskNetwork: 'linea-mainnet',
    explorerDomain: 'api.lineascan.build',
    explorerBrowserDomain: 'lineascan.build',
    usdcAddress: '0x176211869cA2b568f2A7D4EE941E073a821EE1ff',
    isDev: false,
  },
  [Chain.LINEA_SEPOLIA]: {
    chainType: ChainType.EVM,
    chainId: 59141,
    name: 'Linea Sepolia',
    alchemyNetwork: 'linea-sepolia',
    ankrNetwork: 'linea_sepolia',
    metamaskNetwork: 'linea-sepolia',
    explorerDomain: 'api-sepolia.lineascan.build',
    explorerBrowserDomain: 'sepolia.lineascan.build',
    usdcAddress: undefined,
    isDev: true,
  },

  // Scroll
  [Chain.SCROLL_MAINNET]: {
    chainType: ChainType.EVM,
    chainId: 534352,
    name: 'Scroll',
    alchemyNetwork: 'scroll-mainnet',
    ankrNetwork: 'scroll',
    metamaskNetwork: undefined,
    explorerDomain: 'api.scrollscan.com',
    explorerBrowserDomain: 'scrollscan.com',
    usdcAddress: '0x06eFdBFf2a14a7c8E15944D1F4A48F9F95F663A4',
    isDev: false,
  },
  [Chain.SCROLL_SEPOLIA]: {
    chainType: ChainType.EVM,
    chainId: 534351,
    name: 'Scroll Sepolia',
    alchemyNetwork: 'scroll-sepolia',
    ankrNetwork: 'scroll_sepolia',
    metamaskNetwork: undefined,
    explorerDomain: 'api-sepolia.scrollscan.com',
    explorerBrowserDomain: 'sepolia.scrollscan.com',
    usdcAddress: undefined,
    isDev: true,
  },

  // Monad
  [Chain.MONAD_MAINNET]: {
    chainType: ChainType.EVM,
    chainId: 10000,
    name: 'Monad',
    alchemyNetwork: undefined,
    ankrNetwork: undefined,
    metamaskNetwork: undefined,
    explorerDomain: undefined,
    explorerBrowserDomain: 'explorer.monad.xyz',
    usdcAddress: undefined,
    isDev: false,
  },
  [Chain.MONAD_TESTNET]: {
    chainType: ChainType.EVM,
    chainId: 10001,
    name: 'Monad Testnet',
    alchemyNetwork: undefined,
    ankrNetwork: undefined,
    metamaskNetwork: undefined,
    explorerDomain: undefined,
    explorerBrowserDomain: 'testnet.explorer.monad.xyz',
    usdcAddress: undefined,
    isDev: true,
  },

  // Story Protocol
  [Chain.STORY_MAINNET]: {
    chainType: ChainType.EVM,
    chainId: 1516,
    name: 'Story',
    alchemyNetwork: undefined,
    ankrNetwork: undefined,
    metamaskNetwork: undefined,
    explorerDomain: undefined,
    explorerBrowserDomain: 'explorer.story.foundation',
    usdcAddress: undefined,
    isDev: false,
  },
  [Chain.STORY_TESTNET]: {
    chainType: ChainType.EVM,
    chainId: 1513,
    name: 'Story Testnet',
    alchemyNetwork: undefined,
    ankrNetwork: undefined,
    metamaskNetwork: undefined,
    explorerDomain: undefined,
    explorerBrowserDomain: 'testnet.explorer.story.foundation',
    usdcAddress: undefined,
    isDev: true,
  },

  // Plume Network
  [Chain.PLUME_MAINNET]: {
    chainType: ChainType.EVM,
    chainId: 98865,
    name: 'Plume',
    alchemyNetwork: undefined,
    ankrNetwork: undefined,
    metamaskNetwork: undefined,
    explorerDomain: undefined,
    explorerBrowserDomain: 'explorer.plumenetwork.xyz',
    usdcAddress: '0x222365EF19F7947e5484218551B56bb3965Aa7aF',
    isDev: false,
  },
  [Chain.PLUME_TESTNET]: {
    chainType: ChainType.EVM,
    chainId: 98864,
    name: 'Plume Testnet',
    alchemyNetwork: undefined,
    ankrNetwork: undefined,
    metamaskNetwork: undefined,
    explorerDomain: undefined,
    explorerBrowserDomain: 'testnet.explorer.plumenetwork.xyz',
    usdcAddress: '0xcB5f30e335672893c7eb944B374c196392C19D18',
    isDev: true,
  },

  // Nexus
  [Chain.NEXUS_MAINNET]: {
    chainType: ChainType.EVM,
    chainId: 9999,
    name: 'Nexus',
    alchemyNetwork: undefined,
    ankrNetwork: undefined,
    metamaskNetwork: undefined,
    explorerDomain: undefined,
    explorerBrowserDomain: 'explorer.nexus.xyz',
    usdcAddress: undefined,
    isDev: false,
  },
  [Chain.NEXUS_TESTNET]: {
    chainType: ChainType.EVM,
    chainId: 9998,
    name: 'Nexus Testnet',
    alchemyNetwork: undefined,
    ankrNetwork: undefined,
    metamaskNetwork: undefined,
    explorerDomain: undefined,
    explorerBrowserDomain: 'testnet.explorer.nexus.xyz',
    usdcAddress: undefined,
    isDev: true,
  },

  // HyperEVM
  [Chain.HYPEREVM_MAINNET]: {
    chainType: ChainType.EVM,
    chainId: 998,
    name: 'HyperEVM',
    alchemyNetwork: undefined,
    ankrNetwork: undefined,
    metamaskNetwork: undefined,
    explorerDomain: undefined,
    explorerBrowserDomain: 'app.hyperliquid.xyz/explorer',
    usdcAddress: '0xb88339CB7199b77E23DB6E890353E22632Ba630f',
    isDev: false,
  },
  [Chain.HYPEREVM_TESTNET]: {
    chainType: ChainType.EVM,
    chainId: 997,
    name: 'HyperEVM Testnet',
    alchemyNetwork: undefined,
    ankrNetwork: undefined,
    metamaskNetwork: undefined,
    explorerDomain: undefined,
    explorerBrowserDomain: 'app.hyperliquid-testnet.xyz/explorer',
    usdcAddress: '0x2B3370eE501B4a559b57D449569354196457D8Ab',
    isDev: true,
  },

  // Sonic
  [Chain.SONIC_MAINNET]: {
    chainType: ChainType.EVM,
    chainId: 146,
    name: 'Sonic',
    alchemyNetwork: undefined,
    ankrNetwork: undefined,
    metamaskNetwork: undefined,
    explorerDomain: undefined,
    explorerBrowserDomain: 'sonicscan.org',
    usdcAddress: '0x29219dd400f2Bf60E5a23d13Be72B486D4038894',
    isDev: false,
  },
  [Chain.SONIC_TESTNET]: {
    chainType: ChainType.EVM,
    chainId: 64165,
    name: 'Sonic Testnet',
    alchemyNetwork: undefined,
    ankrNetwork: undefined,
    metamaskNetwork: undefined,
    explorerDomain: undefined,
    explorerBrowserDomain: 'testnet.sonicscan.org',
    usdcAddress: '0x0BA304580ee7c9a980CF72e55f5Ed2E9fd30Bc51',
    isDev: true,
  },
  [Chain.SONIC_BLAZE]: {
    chainType: ChainType.EVM,
    chainId: 57054,
    name: 'Sonic Blaze',
    alchemyNetwork: undefined,
    ankrNetwork: undefined,
    metamaskNetwork: undefined,
    explorerDomain: undefined,
    explorerBrowserDomain: 'blaze.sonicscan.org',
    usdcAddress: '0xA4879Fed32Ecbef99399e5cbC247E533421C4eC6',
    isDev: true,
  },

  // Unichain
  [Chain.UNICHAIN_MAINNET]: {
    chainType: ChainType.EVM,
    chainId: 1,
    name: 'Unichain',
    alchemyNetwork: undefined,
    ankrNetwork: undefined,
    metamaskNetwork: undefined,
    explorerDomain: undefined,
    explorerBrowserDomain: 'uniscan.xyz',
    usdcAddress: '0x078D782b760474a361dDA0AF3839290b0EF57AD6',
    isDev: false,
  },
  [Chain.UNICHAIN_SEPOLIA]: {
    chainType: ChainType.EVM,
    chainId: 1301,
    name: 'Unichain Sepolia',
    alchemyNetwork: undefined,
    ankrNetwork: undefined,
    metamaskNetwork: undefined,
    explorerDomain: undefined,
    explorerBrowserDomain: 'sepolia.uniscan.xyz',
    usdcAddress: '0x31d0220469e10c4E71834a79b1f276E153D00a2D',
    isDev: true,
  },

  // World Chain
  [Chain.WORLD_MAINNET]: {
    chainType: ChainType.EVM,
    chainId: 480,
    name: 'World Chain',
    alchemyNetwork: undefined,
    ankrNetwork: undefined,
    metamaskNetwork: undefined,
    explorerDomain: undefined,
    explorerBrowserDomain: 'worldscan.org',
    usdcAddress: '0x79A02482A880bCe3F13E09da970dC34dB4cD24D1',
    isDev: false,
  },

  // XDC Network
  [Chain.XDC_MAINNET]: {
    chainType: ChainType.EVM,
    chainId: 50,
    name: 'XDC Network',
    alchemyNetwork: undefined,
    ankrNetwork: undefined,
    metamaskNetwork: undefined,
    explorerDomain: undefined,
    explorerBrowserDomain: 'xdcscan.io',
    usdcAddress: undefined,
    isDev: false,
  },

  // Ink
  [Chain.INK_TESTNET]: {
    chainType: ChainType.EVM,
    chainId: 763373,
    name: 'Ink Testnet',
    alchemyNetwork: undefined,
    ankrNetwork: undefined,
    metamaskNetwork: undefined,
    explorerDomain: undefined,
    explorerBrowserDomain: 'explorer.inkonchain.com',
    usdcAddress: '0xFabab97dCE620294D2B0b0e46C68964e326300Ac',
    isDev: true,
  },

  // Fetch.ai
  [Chain.FETCH_MAINNET]: {
    chainType: ChainType.EVM,
    chainId: 2154,
    name: 'Fetch.ai',
    alchemyNetwork: undefined,
    ankrNetwork: undefined,
    metamaskNetwork: undefined,
    explorerDomain: undefined,
    explorerBrowserDomain: 'explore.fetch.ai',
    usdcAddress: undefined,
    isDev: false,
  },
  [Chain.FETCH_TESTNET]: {
    chainType: ChainType.EVM,
    chainId: 2153,
    name: 'Fetch.ai Testnet',
    alchemyNetwork: undefined,
    ankrNetwork: undefined,
    metamaskNetwork: undefined,
    explorerDomain: undefined,
    explorerBrowserDomain: 'explore-testnet.fetch.ai',
    usdcAddress: undefined,
    isDev: true,
  },

  // Gensyn
  [Chain.GENSYN_MAINNET]: {
    chainType: ChainType.EVM,
    chainId: 8888,
    name: 'Gensyn',
    alchemyNetwork: undefined,
    ankrNetwork: undefined,
    metamaskNetwork: undefined,
    explorerDomain: undefined,
    explorerBrowserDomain: 'explorer.gensyn.ai',
    usdcAddress: undefined,
    isDev: false,
  },
  [Chain.GENSYN_TESTNET]: {
    chainType: ChainType.EVM,
    chainId: 8887,
    name: 'Gensyn Testnet',
    alchemyNetwork: undefined,
    ankrNetwork: undefined,
    metamaskNetwork: undefined,
    explorerDomain: undefined,
    explorerBrowserDomain: 'testnet.explorer.gensyn.ai',
    usdcAddress: undefined,
    isDev: true,
  },

  // Ritual
  [Chain.RITUAL_MAINNET]: {
    chainType: ChainType.EVM,
    chainId: 7777,
    name: 'Ritual',
    alchemyNetwork: undefined,
    ankrNetwork: undefined,
    metamaskNetwork: undefined,
    explorerDomain: undefined,
    explorerBrowserDomain: 'explorer.ritual.net',
    usdcAddress: undefined,
    isDev: false,
  },
  [Chain.RITUAL_TESTNET]: {
    chainType: ChainType.EVM,
    chainId: 7776,
    name: 'Ritual Testnet',
    alchemyNetwork: undefined,
    ankrNetwork: undefined,
    metamaskNetwork: undefined,
    explorerDomain: undefined,
    explorerBrowserDomain: 'testnet.explorer.ritual.net',
    usdcAddress: undefined,
    isDev: true,
  },

  // Solana
  [Chain.SOLANA_MAINNET]: {
    chainType: ChainType.SOLANA,
    chainId: -101,
    name: 'Solana',
    alchemyNetwork: 'solana-mainnet',
    ankrNetwork: 'solana',
    metamaskNetwork: undefined,
    explorerDomain: undefined,
    explorerBrowserDomain: 'explorer.solana.com',
    usdcAddress: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
    isDev: false,
  },
  [Chain.SOLANA_DEVNET]: {
    chainType: ChainType.SOLANA,
    chainId: -102,
    name: 'Solana Devnet',
    alchemyNetwork: 'solana-devnet',
    ankrNetwork: 'solana_devnet',
    metamaskNetwork: undefined,
    explorerDomain: undefined,
    explorerBrowserDomain: 'explorer.solana.com/?cluster=devnet',
    usdcAddress: '4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU',
    isDev: true,
  },
  [Chain.SOLANA_TESTNET]: {
    chainType: ChainType.SOLANA,
    chainId: -103,
    name: 'Solana Testnet',
    alchemyNetwork: 'solana-testnet',
    ankrNetwork: 'solana_testnet',
    metamaskNetwork: undefined,
    explorerDomain: undefined,
    explorerBrowserDomain: 'explorer.solana.com/?cluster=testnet',
    usdcAddress: '4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU',
    isDev: true,
  },

  // Local development
  [Chain.EVM_LOCAL]: {
    chainType: ChainType.EVM,
    chainId: 31337,
    name: 'Local EVM',
    alchemyNetwork: undefined,
    ankrNetwork: undefined,
    metamaskNetwork: undefined,
    explorerDomain: undefined,
    explorerBrowserDomain: undefined,
    usdcAddress: '0x0000000000000000000000000000000000000000',
    isDev: true,
  },
  [Chain.SOLANA_LOCAL]: {
    chainType: ChainType.SOLANA,
    chainId: -104,
    name: 'Local Solana',
    alchemyNetwork: undefined,
    ankrNetwork: undefined,
    metamaskNetwork: undefined,
    explorerDomain: undefined,
    explorerBrowserDomain: undefined,
    usdcAddress: '11111111111111111111111111111111',
    isDev: true,
  },
};
